// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swulscymggxvyxskuibu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dWxzY3ltZ2d4dnl4c2t1aWJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNzgxNDEsImV4cCI6MjA2NjY1NDE0MX0.vlA7zc3_HB3M8xIpvY6HTCtK_s75spkWauB0nHF4LVE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);